server:
  device: cpu
  data_dir  : "./log_funcx_appfl/server"
  output_dir: "./log_funcx_appfl/server"
  s3_bucket: appflx-models
  
clients:
  - name: appfl_test
    endpoint_id: "6c87988d-d067-43c9-a73f-063b51e1b33a"
    device:  cpu
    data_split: 0
    output_dir: "./output"
    data_dir:   "./output"
    get_data:
      script_file: "./datasets/torchvision_datasets.py"
      call:   "get_data"

  - name: appfl_test2
    endpoint_id: "4d34697f-f2e0-41dc-87b4-9821a02c0c0a"
    device:  cpu
    data_split: 0
    output_dir: "./output"
    data_dir:   "./output"
    get_data:
      script_file: "./datasets/torchvision_datasets.py"
      call:   "get_data"