clients:
  - name: appfl_test
    endpoint_id: "6c87988d-d067-43c9-a73f-063b51e1b33a"
    device:  cpu
    data_split: 0
    output_dir: "./output"
    data_dir:   "./output"
    get_data:
      script_file: "../client/datasets/torchvision_datasets.py"
      call:   "get_data"